[package]
name = "hyprqtile"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
hyprland = "0.4.0-alpha.3"

anyhow = "1.0"

tracing = "0.1.41"
tracing-subscriber = "0.3"
